export const Pages_Not_Having_BottomNav_InMobile = [
  "/auth/enter_phone",
  "/auth/otp",
  "/auth/forget-password",
  "/auth/login-enter_password",
  "/auth/signup",
  // "/s/room/[combination]",
  // "/b/room/[combination]",
  // "/h/room/[combination]",
  "/rentals/[id]",
  "/residences/submit",
  "/chats/[id]",
  "/my-trips/[id]",
  "/residences/calendar/edit",
  "/residences/[id]/general-pricing/edit",
  "/general-pricing",
  "/residences/[id]/edit",
  "/profile",
  "/support",
  // Start of Second pages routes
  "/public-faqs",
  "/complaint",
  "/rules",
  "/reserve-cancellation-policy",
  "/about",
  "/contact-us",
  // End of Second pages routes
  "/b-room/[id]/edit",
  "/submit-review",
  "/nowruz-pricing",
  "/admin/login",
  "/admin",
  "/admin/reservations",
  "/admin/residences",
  "/admin/residences/[id]",
  "/admin/users",
];
