export const Routes_Without_Header_InBoth_DesktopAndMobile = [
  // "/",
  "/auth/enter_phone",
  "/auth/otp",
  "/auth/login-enter_password",
  "/auth/forget-password",
  "/auth/signup",
  "/submit-review",
  "/admin/login",
  "/admin",
  "/admin/reservations",
  "/admin/residences",
  "/admin/residences/[id]",
  "/admin/users",
];
