export const Routes_Without_Header_InMobile = [
  // "/404",
  // "/500",
  "/profile",
  // "/s/room/[combination]",
  // "/b/room/[combination]",
  // "/h/room/[combination]",
  "/rentals/[id]",
  "/residences/[id]/rules",
  "/residences/[id]/rules/cancel-reserve",
  "/residences/[id]/facilities",
  "/residences/[id]/comments",
  // "/residences/calendar",
  "/residences/suggest/[id]",
  "/residences/[id]/edit",
  // The page carries its own ModalHeader — back button and «ویرایش تقویم» —
  // so the app header on top of it is a second one.
  "/residences/calendar",
  "/residences/calendar/edit",
  "/residences/submit",
  "/residences/[id]/general-pricing/edit",
  "/general-pricing",
  "/chats/[id]",
  "/b-room/[id]/edit",
  "/nowruz-pricing",
];
