export const residences_amenities = {
  bathroom: "حمام",
  guard: "سرایدار - نگهبان",
  food: "سرو غذا",
  billiard: "میز بیلیارد",
  jacuzzi: "جکوزی",
  sauna: "سونا",
  pool: "استخر",
  barbecue: "کباب پز",
  "squat-toilet": "توالت ایرانی",
  "western-toilet": "توالت فرنگی",
  elevator: "آسانسور",
  parking: "پارکینگ",
  wardrobe: "کمد - دراور",
  "dining-table": "میز نهارخوری",
  furniture: "مبلمان",
  hairdryer: "سشوار",
  iron: "اتو",
  washer: "ماشین لباسشویی",
  vacuum: "جاروبرقی",
  refrigerator: "یخچال",
  microwave: "مایکروفر",
  stove: "اجاق گاز",
  kitchenware: "وسایل آشپزخانه",
  cooling: "سیستم سرمایش",
  heating: "سیستم گرمایشی",
  toiletries: "اقلام بهداشتی",
  internet: "اینترنت",
  tv: "تلویزیون",
  mobile: "آنتن دهی تلفن همراه",
  blanket: "پتو",
  balcony: "تراس (بالکن)",
  mattress: "تشک",
  view: "چشم انداز",
  gym: "سالن بدنسازی",
  breakfast: " صبحانه",
  cosmetics: "لوازم آرایشی و بهداشتی",
  recreational: "وسایل تفریحی",
};
